<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Entity"
                  targetNamespace="http://service.schemas/domain/service/v1" 
                  xmlns:tns="http://service.schemas/domain/service/v1" 
                  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <wsdl:types>
        <xs:schema targetNamespace="http://service.schemas/domain/service/v1" xmlns="http://www.w3.org/2000/10/XMLSchema"
                   elementFormDefault="qualified" attributeFormDefault="unqualified">
          <xs:element name="GetEntityRequest">
            <xs:complexType>
              <xs:sequence>
                <element name="Abc" type="xs:string"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
            <xs:complexType name="complex">
                <xs:sequence>
                    <element name="Def" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:simpleType name="simple">
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="10" />
                    <xs:maxInclusive value="20" />
                </xs:restriction>
            </xs:simpleType>
        </xs:schema>
    </wsdl:types>

</wsdl:definitions>
