<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Entity"
                  targetNamespace="http://service.schemas/domain/service/v1" 
                  xmlns:tns="http://service.schemas/domain/service/v1" 
                  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <wsdl:portType name="FirstService"></wsdl:portType>
    <wsdl:binding name="FirstBinding" type="tns:FirstService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    </wsdl:binding>

    <wsdl:service name="First">
        <wsdl:port name="FirstWS" binding="tns:FirstBinding">
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
